# Generated by Django 3.1.3 on 2020-11-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FicheFrais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=6)),
                ('nb_justificatifs', models.IntegerField()),
                ('montant_valide', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_modif', models.DateField()),
                ('id_etat', models.CharField(default='CR', max_length=2)),
            ],
            options={
                'unique_together': {('mois', 'id')},
            },
        ),
    ]
