# Generated by Django 3.1.4 on 2020-12-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefraishorsforfait',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='LigneFraisForfait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=6)),
                ('quantite', models.PositiveIntegerField()),
                ('frais_forfait', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ppefrais.fraisforfait')),
                ('utilisateur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'mois', 'frais_forfait')},
            },
        ),
    ]
