# Generated by Django 3.1.5 on 2021-01-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefraisforfait',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
