# Generated by Django 3.1.5 on 2021-01-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0002_auto_20210111_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefraisforfait',
            name='frais_forfait',
            field=models.CharField(choices=[('ETP', 'Forfait étape'), ('KM', 'Frais kilométrique'), ('NUI', 'Nuitée hôtel'), ('REP', 'Repas restaurant')], default=None, max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='lignefraisforfait',
            unique_together={('fiche', 'frais_forfait')},
        ),
    ]
