# Generated by Django 3.1.4 on 2020-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0002_auto_20201214_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefraisforfait',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
