# Generated by Django 3.1.3 on 2020-11-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0002_auto_20201118_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichefrais',
            old_name='id_etat',
            new_name='etat',
        ),
    ]
