# Generated by Django 3.1.3 on 2020-11-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0003_auto_20201118_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='fichefrais',
            name='visiteur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ppefrais.visiteur'),
        ),
        migrations.AlterUniqueTogether(
            name='fichefrais',
            unique_together={('mois', 'visiteur')},
        ),
    ]
