# Generated by Django 3.1.5 on 2021-01-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0004_auto_20210106_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichefrais',
            name='etat',
            field=models.CharField(choices=[('CL', 'Saisie clôturée'), ('CR', 'Fiche créée, saisie en cours'), ('RB', 'Remboursée'), ('VA', 'Validée et mise en paiement')], default='CR', max_length=3),
        ),
        migrations.DeleteModel(
            name='Etat',
        ),
    ]
