# Generated by Django 3.1.3 on 2020-11-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0004_auto_20201118_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichefrais',
            name='etat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ppefrais.etat'),
        ),
    ]
