# Generated by Django 3.1.3 on 2020-11-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0005_auto_20201118_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraisForfait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visiteur',
            name='login',
        ),
        migrations.AddField(
            model_name='visiteur',
            name='adresse',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='code_postal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='visiteur',
            name='date_embauhe',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='etat',
            name='libelle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fichefrais',
            name='date_modif',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fichefrais',
            name='montant_valide',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fichefrais',
            name='nb_justificatifs',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='nom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='prenom',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='LigneFraisHorsForfait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=6)),
                ('quantite', models.PositiveIntegerField()),
                ('frais_forfait', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ppefrais.fraisforfait')),
                ('visiteur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ppefrais.visiteur')),
            ],
            options={
                'unique_together': {('visiteur', 'mois', 'frais_forfait')},
            },
        ),
    ]
