# Generated by Django 3.1.3 on 2020-11-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0007_auto_20201125_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='code_postal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_embauche',
            field=models.DateField(null=True),
        ),
    ]
