# Generated by Django 3.1.3 on 2020-11-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0008_auto_20201125_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='statutId',
        ),
        migrations.AddField(
            model_name='fichefrais',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ppefrais.utilisateur'),
        ),
        migrations.AddField(
            model_name='lignefraishorsforfait',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ppefrais.utilisateur'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('VS', 'Visiteur'), ('CP', 'Comptable')], default='CP', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='fichefrais',
            unique_together={('mois', 'utilisateur')},
        ),
        migrations.AlterUniqueTogether(
            name='lignefraishorsforfait',
            unique_together={('utilisateur', 'mois', 'frais_forfait')},
        ),
        migrations.DeleteModel(
            name='Statut',
        ),
        migrations.RemoveField(
            model_name='fichefrais',
            name='visiteur',
        ),
        migrations.RemoveField(
            model_name='lignefraishorsforfait',
            name='visiteur',
        ),
        migrations.DeleteModel(
            name='Visiteur',
        ),
    ]
