# Generated by Django 3.1.3 on 2020-11-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0009_auto_20201125_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='statut',
            field=models.CharField(choices=[('Visiteur', 'Vst'), ('Comptable', 'Cpt')], default='Comptable', max_length=9),
        ),
    ]
