# Generated by Django 3.1.4 on 2020-12-06 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0010_auto_20201125_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='date_embauche',
            field=models.DateField(default=datetime.datetime(2020, 12, 6, 12, 46, 2, 731462), null=True),
        ),
    ]
