# Generated by Django 3.1.4 on 2020-12-06 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppefrais', '0011_auto_20201206_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_embauche',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 12, 6, 12, 49, 33, 498688), null=True),
        ),
    ]
